### PR TITLE
Update to diag tables for suites using RUC LSM: hrrr, hrrr_stoch and rap

### PR DESCRIPTION
**Pull request by tanyasmirnova**
This PR includes additional variables specific to RUC LSM.

### CODE REVIEW

**Comment by tanyasmirnova** [comment]
@SamuelTrahanNOAA Sam, I also updated diag_table_rap, and added one more variable to all three diag tables using RUC LSM. Thank you!

**Comment by SamuelTrahanNOAA** [comment]
I don't know which diag_tables you want me to update. I have updated hrrr, hrrr_stoch, and rap.

**Comment by tanyasmirnova** [comment]
@SamuelTrahanNOAA Sam, yes, these three tables. Could you please compare what we have in the merged code with my PR?

**Comment by SamuelTrahanNOAA** [comment]
Your PR updates 893 files, so it would be difficult to compare everything. You need to rebase to the correct branch, update-rrfs-dev-20220614

**Comment by tanyasmirnova** [comment]
Please, see PR #4. The first one was to the wrong branch.

**Pull request closed without merging**
